In [13]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, LabelBinarizer, OneHotEncoder

In [3]:
df = pd.read_csv(r'C:\Users\Darab Store\Desktop\ML-projects\Git-Hub\Tutorials\sickit-learn\Data-Encoder\train.csv')
df.drop('id', axis=1, inplace=True)
df

Gender        Age    Height      Weight family_history_with_overweight  \
0        Male  24.443011  1.699998   81.669950                            yes   
1      Female  18.000000  1.560000   57.000000                            yes   
2      Female  18.000000  1.711460   50.165754                            yes   
3      Female  20.952737  1.710730  131.274851                            yes   
4        Male  31.641081  1.914186   93.798055                            yes   
...       ...        ...       ...         ...                            ...   
20753    Male  25.137087  1.766626  114.187096                            yes   
20754    Male  18.000000  1.710000   50.000000                             no   
20755    Male  20.101026  1.819557  105.580491                            yes   
20756    Male  33.852953  1.700000   83.520113                            yes   
20757    Male  26.680376  1.816547  118.134898                            yes   

      FAVC      FCVC       NCP        CAEC SMOKE      CH2O SCC       FAF  \
0      yes  2.000000  2.983297   Sometimes    no  2.763573  no  0.000000   
1      yes  2.000000  3.000000  Frequently    no  2.000000  no  1.000000   
2      yes  1.880534  1.411685   Sometimes    no  1.910378  no  0.866045   
3      yes  3.000000  3.000000   Sometimes    no  1.674061  no  1.467863   
4      yes  2.679664  1.971472   Sometimes    no  1.979848  no  1.967973   
...    ...       ...       ...         ...   ...       ...  ..       ...   
20753  yes  2.919584  3.000000   Sometimes    no  2.151809  no  1.330519   
20754  yes  3.000000  4.000000  Frequently    no  1.000000  no  2.000000   
20755  yes  2.407817  3.000000   Sometimes    no  2.000000  no  1.158040   
20756  yes  2.671238  1.971472   Sometimes    no  2.144838  no  0.000000   
20757  yes  3.000000  3.000000   Sometimes    no  2.003563  no  0.684487   

            TUE       CALC                 MTRANS           NObeyesdad  
0      0.976473  Sometimes  Public_Transportation  Overweight_Level_II  
1      1.000000         no             Automobile        Normal_Weight  
2      1.673584         no  Public_Transportation  Insufficient_Weight  
3      0.780199  Sometimes  Public_Transportation     Obesity_Type_III  
4      0.931721  Sometimes  Public_Transportation  Overweight_Level_II  
...         ...        ...                    ...                  ...  
20753  0.196680  Sometimes  Public_Transportation      Obesity_Type_II  
20754  1.000000  Sometimes  Public_Transportation  Insufficient_Weight  
20755  1.198439         no  Public_Transportation      Obesity_Type_II  
20756  0.973834         no             Automobile  Overweight_Level_II  
20757  0.713823  Sometimes  Public_Transportation      Obesity_Type_II  

[20758 rows x 17 columns]

# Using LabelEncoder

In [6]:
le = LabelEncoder()
le.fit_transform(df['NObeyesdad'])

array([6, 1, 0, ..., 3, 6, 3])

In [7]:
# LabelEncode encode target as following list printed below:

list(le.classes_)


# there is one disadvantage about this method. we can't realize importance of each value.
# so it is better for us and machines to don't use this method for multiclass classification tasks.

['Insufficient_Weight',
 'Normal_Weight',
 'Obesity_Type_I',
 'Obesity_Type_II',
 'Obesity_Type_III',
 'Overweight_Level_I',
 'Overweight_Level_II']

# Using LabelBinarizer

In [9]:
lb = LabelBinarizer()
lb.fit_transform(df['Gender'])

# male = 1, female = 0

array([[1],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

# Using One-Hot-Encoder

In [47]:
oe = OneHotEncoder(handle_unknown='ignore' ,sparse_output=False).set_output(transform='pandas')
oe.fit_transform(df[['CAEC']])

CAEC_Always  CAEC_Frequently  CAEC_Sometimes  CAEC_no
0              0.0              0.0             1.0      0.0
1              0.0              1.0             0.0      0.0
2              0.0              0.0             1.0      0.0
3              0.0              0.0             1.0      0.0
4              0.0              0.0             1.0      0.0
...            ...              ...             ...      ...
20753          0.0              0.0             1.0      0.0
20754          0.0              1.0             0.0      0.0
20755          0.0              0.0             1.0      0.0
20756          0.0              0.0             1.0      0.0
20757          0.0              0.0             1.0      0.0

[20758 rows x 4 columns]

In [49]:
df['CAEC'].unique()

['Sometimes', 'Frequently', 'no', 'Always']
Categories (4, object): ['Always', 'Frequently', 'Sometimes', 'no']

In [50]:
# as you can see, onehotencoder encode data to 0, 1 for each of unique values.

# Ordinal Encoder

In [52]:
df['CAEC'].unique()

['Sometimes', 'Frequently', 'no', 'Always']
Categories (4, object): ['Always', 'Frequently', 'Sometimes', 'no']

In [54]:
caec = ['no', 'Sometimes', 'Frequently', 'Always']

In [56]:
oe = OrdinalEncoder(categories=[caec])
oe.fit_transform(df[['CAEC']])

array([[1.],
       [2.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [57]:
df['CAEC'].head()

# sometimes=1 , frequently=2, etc.

0     Sometimes
1    Frequently
2     Sometimes
3     Sometimes
4     Sometimes
Name: CAEC, dtype: category
Categories (4, object): ['Always', 'Frequently', 'Sometimes', 'no']